### ISSUE TITLE
Brake notch at B3 and B4 reports the same value

### ISSUE THREAD

**Issue by pasteur90** [GMMan/dengo-plug-and-play-controller#3]
Hi! Thank you for uploading and sharing this great project!
Playing the DDG games with the controller on the PC, I noticed a minor problem.
The controller reports the same value both on B3 and B4 notch.

Does it has something to do with the [binary blob](https://github.com/GMMan/dengo-plug-and-play-controller/blob/master/payload/input_relay)?

**Comment by GMMan** [comment]
Does it work properly playing the built in DDG Final?

**Comment by pasteur90** [comment]
No, it jumps from B3 to B5.
Could it be faulty hardware of mine?

**Comment by GMMan** [comment]
That sounds likely. Perhaps one of the resistors responsible has drifted, or there's some oxidization on the pad.

**Comment by pasteur90** [comment]
Thank you for the suggestion.
Just took apart and reassembled the console.
The problem has gone.
